### ISSUE TITLE
external option is ignored

### ISSUE THREAD

**Issue by gluck** [egoist/play-esbuild#3]
I wanted to use the playground to check esbuild output when transpiling TS imports, but I can't because `external` option is ignored, hence all imports are bundled.
I believe it's caused by the custom plugin redirecting all imports to unpkg URL.
Don't know if there's a better way to fix it than manually checking external option in that callback, lmk what you think and I can write down a PR for it.

**Comment by egoist** [comment]
> Don't know if there's a better way to fix it than manually checking external option in that callback

That's the best way to do it I guess, PR welcome
