### ISSUE TITLE
Update URL in GitHub About section

### ISSUE THREAD

**Issue by karlhorky** [egoist/play-esbuild#7]
Hi @egoist, first of all, thanks for this and all of your other work in the industry, really great! 🙌

I see that the existing URL in the About section on GitHub (on the top right on desktop) is set to https://esbuild.egoist.sh/ . However this URL redirects to https://esbuild.egoist.dev/ - maybe the `.sh` URL should be replaced with the `.dev` one?

**Comment by karlhorky** [comment]
@egoist I wasn't referring to the readme URLs with this issue - I was referring to the URL in the About section, which appears to be unchanged:

![Screenshot_20230210-072339~2](https://user-images.githubusercontent.com/1935696/218018869-bb524b76-edf8-4dd7-8202-7a2e2770ff93.png)

**Comment by egoist** [comment]
thanks, updated

**Comment by karlhorky** [comment]
Glad to help, thanks for updating!
